name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                compiler: [gcc]
        env:
            CC: ${{ matrix.compiler }}
        steps:
            - uses: actions/checkout@v3
            - run: sudo apt-get update && sudo apt-get install -y gcc-multilib cpio qemu-system-x86 grub2 mtools xorriso
            - run: export ARCH=i386
            - run: scripts/build.sh && scripts/cdrom.sh
            - name: Upload files to a GitHub release
              uses: svenstaro/upload-release-action@2.3.0
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: psychix.iso
                asset_name: psychix.iso
                tag: ${{ github.ref }}
                overwrite: true
                body: "Psychix latest version; Compiled through cloud..."
