name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                compiler: [gcc]
        env:
            CC: ${{ matrix.compiler }}
        steps:
            - uses: actions/checkout@v3
            - run: sudo apt-get update && sudo apt-get install -y gcc-multilib wget cpio qemu-system-x86 grub2 mtools xorriso
            - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            - run: sudo apt-get update
            - run: sudo apt-get install libc6-dev=2.34-0ubuntu1~21.10.1

            - run: make CC=gcc
            - run: nm -n kernel/kernel | awk 'NF==3'
            - run: make test
              timeout-minutes: 1
            - run: grub-file --is-x86-multiboot kernel/kernel
            - run: make cdrom.iso
